name: Otomatik Gunluk Video

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  video-uret:
    runs-on: ubuntu-latest
    steps:
      - name: Depodaki Kodlari Al
        uses: actions/checkout@v4

      - name: Python Ortamini Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerekli Python Kutuphanelerini Yukle
        run: |
          pip install gTTS

      - name: FFmpeg Aracini Yukle
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Botu Calistir ve Videoyu Uret
        run: |
          python bot.py

      - name: Uretilen Videoyu Kaydet (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: Gunluk-Uretilen-Video
          path: '*.mp4'
